# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='msg.proto',
  package='server',
  serialized_pb='\n\tmsg.proto\x12\x06server\"\xf2\x01\n\x07Request\x12\x0b\n\x03tag\x18\x01 \x01(\x05\x12\"\n\x04verb\x18\x02 \x01(\x0e\x32\x14.server.Request.Verb\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x0c\x12\x11\n\tother_tag\x18\x06 \x01(\x05\x12\x0e\n\x06offset\x18\x07 \x01(\x05\x12\x0b\n\x03rev\x18\t \x01(\x03\"i\n\x04Verb\x12\x07\n\x03GET\x10\x01\x12\x07\n\x03SET\x10\x02\x12\x07\n\x03\x44\x45L\x10\x03\x12\x07\n\x03REV\x10\x05\x12\x08\n\x04WAIT\x10\x06\x12\x07\n\x03NOP\x10\x07\x12\x08\n\x04WALK\x10\t\x12\n\n\x06GETDIR\x10\x0e\x12\x08\n\x04STAT\x10\x10\x12\n\n\x06\x41\x43\x43\x45SS\x10\x63\"\xc8\x02\n\x08Response\x12\x0b\n\x03tag\x18\x01 \x01(\x05\x12\r\n\x05\x66lags\x18\x02 \x01(\x05\x12\x0b\n\x03rev\x18\x03 \x01(\x03\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\r\n\x05value\x18\x06 \x01(\x0c\x12\x0b\n\x03len\x18\x08 \x01(\x05\x12&\n\x08\x65rr_code\x18\x64 \x01(\x0e\x32\x14.server.Response.Err\x12\x12\n\nerr_detail\x18\x65 \x01(\t\"\xac\x01\n\x03\x45rr\x12\t\n\x05OTHER\x10\x7f\x12\x0e\n\nTAG_IN_USE\x10\x01\x12\x10\n\x0cUNKNOWN_VERB\x10\x02\x12\x0c\n\x08READONLY\x10\x03\x12\x0c\n\x08TOO_LATE\x10\x04\x12\x10\n\x0cREV_MISMATCH\x10\x05\x12\x0c\n\x08\x42\x41\x44_PATH\x10\x06\x12\x0f\n\x0bMISSING_ARG\x10\x07\x12\t\n\x05RANGE\x10\x08\x12\n\n\x06NOTDIR\x10\x14\x12\t\n\x05ISDIR\x10\x15\x12\t\n\x05NOENT\x10\x16')



_REQUEST_VERB = descriptor.EnumDescriptor(
  name='Verb',
  full_name='server.Request.Verb',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GET', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SET', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEL', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REV', index=3, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WAIT', index=4, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOP', index=5, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WALK', index=6, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GETDIR', index=7, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STAT', index=8, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACCESS', index=9, number=99,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=159,
  serialized_end=264,
)

_RESPONSE_ERR = descriptor.EnumDescriptor(
  name='Err',
  full_name='server.Response.Err',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='OTHER', index=0, number=127,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TAG_IN_USE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNKNOWN_VERB', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READONLY', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TOO_LATE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REV_MISMATCH', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAD_PATH', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MISSING_ARG', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RANGE', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOTDIR', index=9, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ISDIR', index=10, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOENT', index=11, number=22,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=423,
  serialized_end=595,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='server.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tag', full_name='server.Request.tag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='verb', full_name='server.Request.verb', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='path', full_name='server.Request.path', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='server.Request.value', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='other_tag', full_name='server.Request.other_tag', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='server.Request.offset', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rev', full_name='server.Request.rev', index=6,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_VERB,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=264,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='server.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tag', full_name='server.Response.tag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='server.Response.flags', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rev', full_name='server.Response.rev', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='path', full_name='server.Response.path', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='server.Response.value', index=4,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='len', full_name='server.Response.len', index=5,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='err_code', full_name='server.Response.err_code', index=6,
      number=100, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=127,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='err_detail', full_name='server.Response.err_detail', index=7,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_ERR,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=267,
  serialized_end=595,
)

_REQUEST.fields_by_name['verb'].enum_type = _REQUEST_VERB
_REQUEST_VERB.containing_type = _REQUEST;
_RESPONSE.fields_by_name['err_code'].enum_type = _RESPONSE_ERR
_RESPONSE_ERR.containing_type = _RESPONSE;
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:server.Request)

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:server.Response)

# @@protoc_insertion_point(module_scope)
